import random
import copy
from Agents import *

class deck:
    def __init__(self, cards, deck_schema, top_card):
        self.cards = cards
        self.deck_schema = deck_schema
        self.top_card = top_card
        
    def reset(self):
        deck = []
        
              
        #for card in hand:
            
        
        deck = copy.deepcopy(self.deck_schema)
        random.shuffle(deck)
        self.cards = deck
        
    
        
        
Deck = deck(
    cards = [],
    
    deck_schema = [
        'RED 1',
        'RED 2',
        'RED 3',
        'RED 4',
        'RED 5',
        'RED 6',
        'RED 7',
        'RED 8',
        'RED 9',
        'YELLOW 1',
        'YELLOW 2',
        'YELLOW 3',
        'YELLOW 4',
        'YELLOW 5',
        'YELLOW 6',
        'YELLOW 7',
        'YELLOW 8',
        'YELLOW 9',
        'BLUE 1',
        'BLUE 2',
        'BLUE 3',
        'BLUE 4',
        'BLUE 5',
        'BLUE 6',
        'BLUE 7',
        'BLUE 8',
        'BLUE 9',
        'GREEN 1',
        'GREEN 2',
        'GREEN 3',
        'GREEN 4',
        'GREEN 5',
        'GREEN 6',
        'GREEN 7',
        'GREEN 8',
        'GREEN 9',
    ],
    
    top_card = '',
)

deck_schema_complex = [
    ["RED-0-1"],
    ["RED-1-1"],
    ["RED-1-2"],
    ["RED-2-1"],
    ["RED-2-2"],
    ["RED-3-1"],
    ["RED-3-2"],
    ["RED-4-1"],
    ["RED-4-2"],
    ["RED-5-1"],
    ["RED-5-2"],
    ["RED-6-1"],
    ["RED-6-2"],
    ["RED-7-1"],
    ["RED-7-2"],
    ["RED-8-1"],
    ["RED-8-2"],
    ["RED-9-1"],
    ["RED-9-2"],
    ["RED-SKIP-1"],
    ["RED-SKIP-2"],
    ["RED-REVERSE-1"],
    ["RED-REVERSE-2"],
    ["RED-PLUS2-1"],
    ["RED-PLUS2-2"],
    ["YELLOW-0-1"],
    ["YELLOW-1-1"],
    ["YELLOW-1-2"],
    ["YELLOW-2-1"],
    ["YELLOW-2-2"],
    ["YELLOW-3-1"],
    ["YELLOW-3-2"],
    ["YELLOW-4-1"],
    ["YELLOW-4-2"],
    ["YELLOW-5-1"],
    ["YELLOW-5-2"],
    ["YELLOW-6-1"],
    ["YELLOW-6-2"],
    ["YELLOW-7-1"],
    ["YELLOW-7-2"],
    ["YELLOW-8-1"],
    ["YELLOW-8-2"],
    ["YELLOW-9-1"],
    ["YELLOW-9-2"],
    ["YELLOW-SKIP-1"],
    ["YELLOW-SKIP-2"],
    ["YELLOW-REVERSE-1"],
    ["YELLOW-REVERSE-2"],
    ["YELLOW-PLUS2-1"],
    ["YELLOW-PLUS2-2"],
    ["BLUE-0-1"],
    ["BLUE-1-1"],
    ["BLUE-1-2"],
    ["BLUE-2-1"],
    ["BLUE-2-2"],
    ["BLUE-3-1"],
    ["BLUE-3-2"],
    ["BLUE-4-1"],
    ["BLUE-4-2"],
    ["BLUE-5-1"],
    ["BLUE-5-2"],
    ["BLUE-6-1"],
    ["BLUE-6-2"],
    ["BLUE-7-1"],
    ["BLUE-7-2"],
    ["BLUE-8-1"],
    ["BLUE-8-2"],
    ["BLUE-9-1"],
    ["BLUE-9-2"],
    ["BLUE-SKIP-1"],
    ["BLUE-SKIP-2"],
    ["BLUE-REVERSE-1"],
    ["BLUE-REVERSE-2"],
    ["BLUE-PLUS2-1"],
    ["BLUE-PLUS2-2"],
    ["GREEN-0-1"],
    ["GREEN-1-1"],
    ["GREEN-1-2"],
    ["GREEN-2-1"],
    ["GREEN-2-2"],
    ["GREEN-3-1"],
    ["GREEN-3-2"],
    ["GREEN-4-1"],
    ["GREEN-4-2"],
    ["GREEN-5-1"],
    ["GREEN-5-2"],
    ["GREEN-6-1"],
    ["GREEN-6-2"],
    ["GREEN-7-1"],
    ["GREEN-7-2"],
    ["GREEN-8-1"],
    ["GREEN-8-2"],
    ["GREEN-9-1"],
    ["GREEN-9-2"],
    ["GREEN-SKIP-1"],
    ["GREEN-SKIP-2"],
    ["GREEN-REVERSE-1"],
    ["GREEN-REVERSE-2"],
    ["GREEN-PLUS2-1"],
    ["GREEN-PLUS2-2"],
    ["PLUS4-1"],
    ["PLUS4-2"],
    ["PLUS4-3"],
    ["PLUS4-4"],
    ["WILDCARD-1"],
    ["WILDCARD-2"],
    ["WILDCARD-3"],
    ["WILDCARD-4"]
],
